### ISSUE TITLE
How to use with netlify-cms?

### ISSUE THREAD

**Issue by VuongVu** [greglobinski/gatsby-starter-hero-blog#18]
I try to integrate with netlify-cms to create posts but the post can't save right place like `content/posts/...` follow our rule. 
This is my config in config.yml:

```
collections:
  - name: "posts"
    label: "Posts"
    folder: "posts/{{year}}-{{month}}-{{day}}--{{title}}"
    slug: "index" // i'm try with slug {{year}}-{{month}}-{{day}}--{{title}}/index
    create: true
    fields:
      - { name: title, label: Title, widget: 'string' }
      - { name: category, label: Category, widget: 'string' }
      - { name: cover, label: Cover, widget: 'string' }
      - { name: author, label: Author, widget: 'string' }
      - { name: body, label: Body, widget: 'markdown' }
```
The post after create not save in subfolder with regex: year-month-day--title/index.md
Plz give me the solution for it.
